core_arena: Configuration functions.
Configuration functions.
User functions
Functions for setting up and tearing down the arenas.
Macros
#define CHECK_MEM_AVAIL(mem_need, mem_object)
Functions
static void _arena_teardown (void)
void arena_init_arenas (size_t count)
Initializes the number of arenas.
Variables
static bool arenas_initialized =false
Detailed Description
Functions for setting up and tearing down the arenas.
Macro Definition Documentation
CHECK_MEM_AVAIL
#define CHECK_MEM_AVAIL (mem_need, mem_object)
Value:
    do {\
    if (tot_mem_usage > ARENAS_MAX_ALLOC - mem_need ) {\
        _logmsg_write(emsg2,#mem_object);\
        exit(EXIT_FAILURE);\
    }\
} while (0)
Definition at line 670 of file core_arena.c.
Function Documentation
_arena_teardown()
static void _arena_teardown (void) static
Definition at line 645 of file core_arena.c.
{
    free(first);
    free(arenas);
#ifndef CORE_ARENA_NO_LOGGING
    if (core_arena_log_level >= LOG_CHUNK_MALLOCS  ) {
        free(arenas_mem_malloced);
        free(arenas_mem_malloced_count );
        free(arenas_mem_mmapped );
        free(arenas_mem_mmapped_count );
        free(arenas_max_chunk_size );
    }
    if (core_arena_log_level >= FULL_ARENA_LOGGING  ) {
        free(arenas_mem_served );
        free(arenas_mem_served_count);
        free(arenas_max_mem_request);
        free(arenas_min_mem_request);
        free(arenas_avg_mem_request);
    }
#endif
}
References arenas, arenas_avg_mem_request, arenas_max_chunk_size, arenas_max_mem_request, arenas_mem_malloced, arenas_mem_malloced_count, arenas_mem_mmapped, arenas_mem_mmapped_count, arenas_mem_served, arenas_mem_served_count, arenas_min_mem_request, core_arena_log_level, first, FULL_ARENA_LOGGING, and LOG_CHUNK_MALLOCS.
Referenced by arena_init_arenas().
arena_init_arenas()
void arena_init_arenas (size_t count)
Initializes the number of arenas.
Sets a static variable, to show we are initiated. creates arrays fit for the number of arenas installs an exit handler to take down the arenas on exit. Determines logging options if logging is compiled in. Gets the amount of phys_avail memory.
Parameters
count 1 larger than the last arena, starting at zero.
Todo:
Definition at line 689 of file core_arena.c.
{
    static const char *emsg = "arena_init_arenas: Calloc couldn't allocate memory for %s array." ;
    static const char *emsg2 ="arena_init_arenas: Out of memory not enough free memory to allocates for %s.\n";
    size_t memory_consumption;
    assert( count > 0 ) ;
    ARENAS_MAX = count ;
    ARENAS_MAX_ALLOC = ram_avail() ;
    memory_consumption = ARENAS_MAX * sizeof(Arena) ;
    CHECK_MEM_AVAIL(memory_consumption,first);
    first = calloc(ARENAS_MAX, sizeof(Arena)) ;
    if (!first) {
        _errmsg_write( emsg,"first");
        exit(EXIT_FAILURE);
    }
    tot_mem_usage += memory_consumption ;
    memory_consumption = ARENAS_MAX * sizeof(Arena) ;
    CHECK_MEM_AVAIL(memory_consumption,arenas);
    arenas  = calloc(ARENAS_MAX, sizeof(Arena*)) ;
    if (!arenas) {
        _errmsg_write( emsg,"arenas");
        exit(EXIT_FAILURE);
    }
    tot_mem_usage += memory_consumption ;
    memory_consumption= ARENAS_MAX * sizeof(size_t ) ;
    CHECK_MEM_AVAIL(memory_consumption,arena_chunk_sz);
    arena_chunk_sz  = calloc(ARENAS_MAX, sizeof(size_t)) ;
    if (!arena_chunk_sz) {
        _errmsg_write( emsg,"arena_chunk_sz");
        exit(EXIT_FAILURE);
    }
    tot_mem_usage += memory_consumption ;
#ifndef CORE_ARENA_NO_LOGGING
    core_arena_log_level = get_log_level() ;
    if (core_arena_log_level >= LOG_CHUNK_MALLOCS  ) {
        memory_consumption = ARENAS_MAX * sizeof *arenas_mem_malloced ;
        CHECK_MEM_AVAIL(memory_consumption,arenas_mem_malloced);
        arenas_mem_malloced = calloc(ARENAS_MAX, sizeof *arenas_mem_malloced );
        if (!arenas_mem_malloced) {
            _errmsg_write( emsg,"arenas_mem_malloced");
            exit(EXIT_FAILURE);
        }
        tot_mem_usage += memory_consumption ;
        memory_consumption = ARENAS_MAX * sizeof *arenas_mem_malloced_count ;
        CHECK_MEM_AVAIL(memory_consumption,arenas_mem_malloced_count) ;
        arenas_mem_malloced_count = calloc(ARENAS_MAX, sizeof *arenas_mem_malloced_count );
        tot_mem_usage += memory_consumption ;
        memory_consumption = ARENAS_MAX * sizeof *arenas_mem_mmapped ;
        CHECK_MEM_AVAIL(memory_consumption,arenas_mem_mmapped) ;
        arenas_mem_mmapped = calloc(ARENAS_MAX, sizeof *arenas_mem_mmapped );
        if (!arenas_mem_mmapped) {
            _errmsg_write( emsg,"arenas_mem_mmapped");
            exit(EXIT_FAILURE);
        }
        tot_mem_usage += memory_consumption ;
        memory_consumption = ARENAS_MAX * sizeof *arenas_mem_mmapped_count ;
        CHECK_MEM_AVAIL(memory_consumption,arenas_mem_mmapped_count) ;
        arenas_mem_mmapped_count = calloc(ARENAS_MAX, sizeof *arenas_mem_mmapped_count );
        if (!arenas_mem_mmapped) {
            _errmsg_write( emsg,"arenas_mem_mmapped_count");
            exit(EXIT_FAILURE);
        }
        tot_mem_usage += memory_consumption ;
        memory_consumption = ARENAS_MAX * sizeof *arenas_max_chunk_size ;
        CHECK_MEM_AVAIL(memory_consumption,arenas_max_chunk_size) ;
        arenas_max_chunk_size = calloc(ARENAS_MAX, sizeof *arenas_max_chunk_size );
        if (!arenas_mem_mmapped) {
            _errmsg_write( emsg,"arenas_max_chunk_size");
            exit(EXIT_FAILURE);
        }
        tot_mem_usage += memory_consumption ;
    }
    if (core_arena_log_level >= FULL_ARENA_LOGGING  ) {
        memory_consumption = ARENAS_MAX * sizeof *arenas_mem_served ;
        CHECK_MEM_AVAIL(memory_consumption,arenas_mem_served) ;
        arenas_mem_served = calloc(ARENAS_MAX, sizeof *arenas_mem_served );
        if (!arenas_mem_served) {
            _errmsg_write( emsg,"arenas_mem_served");
            exit(EXIT_FAILURE);
        }
        tot_mem_usage += memory_consumption ;
        memory_consumption = ARENAS_MAX * sizeof *arenas_mem_served_count ;
        CHECK_MEM_AVAIL(memory_consumption,arenas_mem_served_count) ;
        arenas_mem_served_count = calloc(ARENAS_MAX, sizeof *arenas_mem_served_count );
        if (!arenas_mem_served_count) {
            _errmsg_write( emsg,"arenas_mem_served_count");
            exit(EXIT_FAILURE);
        }
        tot_mem_usage += memory_consumption ;
        memory_consumption = ARENAS_MAX * sizeof *arenas_max_mem_request ;
        CHECK_MEM_AVAIL(memory_consumption,arenas_max_mem_request) ;
        arenas_max_mem_request = calloc(ARENAS_MAX, sizeof *arenas_max_mem_request );
        if (!arenas_max_mem_request) {
            _errmsg_write( emsg,"arenas_max_mem_request");
            exit(EXIT_FAILURE);
        }
        tot_mem_usage += memory_consumption ;
        memory_consumption = ARENAS_MAX * sizeof *arenas_min_mem_request ;
        CHECK_MEM_AVAIL(memory_consumption,arenas_min_mem_request) ;
        arenas_min_mem_request = calloc(ARENAS_MAX, sizeof *arenas_min_mem_request );
        if (!arenas_min_mem_request) {
            _errmsg_write( emsg,"arenas_min_mem_request");
            exit(EXIT_FAILURE);
        }
        tot_mem_usage += memory_consumption ;
        memory_consumption = ARENAS_MAX * sizeof *arenas_avg_mem_request ;
        CHECK_MEM_AVAIL(memory_consumption,arenas_avg_mem_request) ;
        arenas_avg_mem_request = calloc(ARENAS_MAX, sizeof *arenas_avg_mem_request );
        if (!arenas_avg_mem_request) {
            _errmsg_write( emsg,"arenas_avg_mem_request");
            exit(EXIT_FAILURE);
        }
        tot_mem_usage += memory_consumption ;
    }
#endif
    if (atexit(_arena_teardown)< 0) {
        _errmsg_write("arena_init_arenas: failed to install _arena_teardown down handler. Exiting.%s","\n");
        exit(EXIT_FAILURE);;
    }
    arenas_initialized = true ;
}
References _arena_teardown(), _errmsg_write(), arena_chunk_sz, arenas, arenas_avg_mem_request, arenas_initialized, ARENAS_MAX, ARENAS_MAX_ALLOC, arenas_max_chunk_size, arenas_max_mem_request, arenas_mem_malloced, arenas_mem_malloced_count, arenas_mem_mmapped, arenas_mem_mmapped_count, arenas_mem_served, arenas_mem_served_count, arenas_min_mem_request, CHECK_MEM_AVAIL, core_arena_log_level, first, FULL_ARENA_LOGGING, get_log_level(), LOG_CHUNK_MALLOCS, ram_avail(), and tot_mem_usage.
Variable Documentation
arenas_initialized
bool arenas_initialized =false static
Definition at line 643 of file core_arena.c.
Referenced by arena_alloc(), arena_calloc(), arena_create(), arena_dealloc(), arena_destroy(), and arena_init_arenas().