core_arena: src/core_arena.c File Reference
core_arena.c File Reference
(859f7ea09d922f7d7612f50f96b561a34ed47090)
A general purpose arena allocation strategy that is based on malloc.
#include <core_arena.h>
Data Structures
struct arena
Our struct for book keeping of the arena and its storage .
Macros
#define MAX(a, b) a > b ? a : b;
Simple MAX macro, since no sideeffects.
#define MAX_ENAME 133
Maximum length for an error name.
#define ERR_BUF_SIZE 500
#define LOG_BUF_SIZE 200
#define NO_ARENA_LOGGING 0
Constant for no logging.
#define LOG_CHUNK_MALLOCS 1
Constant for logging allocations of memory for the arenas.
#define FULL_ARENA_LOGGING 2
Constant for logging bothh allocations of memory for the arenas, and the allocations.
#define CHECK_MEM_AVAIL(mem_need, mem_object)
Typedefs
typedef struct arena Arena
Typedef of struct arena.
Functions
static char * _errmsg_format (int err, const char *format, va_list ap)
static void _errmsg_write (const char *format,...)
static char * _logmsg_format (const char *format, va_list ap)
static void _logmsg_write (const char *format,...)
Also used for user errors that doesn't solicit any error number.
long system_page_size (void)
Returns the system viritual memory page_size.
static size_t ram_avail (void)
Returns the physically available ram.
int16_t get_log_level (void)
‍for logging average memory request for each arena
void set_core_arena_log_level (int16_t log_level)
sets the current log_level directly from a program without setting the CORE_ARENA_LOG_LEVEL environment variable.
void report_memory_usage (void)
Reports memory usage, installed by atexit().
static Arena * _arena_init (size_t n, size_t chunk_sz)
Initializes an arena and configures it with the effective chunk_size, and allocates the memory, with malloc(), it also accounts for memory allocated if logging is turned on.
static void * _alloc (Arena **p, size_t mem_sz, size_t n)
Allocates memory from an arena a new arena if necessary for delivering the request.
static void _arena_teardown (void)
void arena_init_arenas (size_t count)
Initializes the number of arenas.
void * arena_alloc (size_t n, size_t mem_sz)
Allocates memory for an object from an arena.
void * arena_calloc (size_t n, size_t nelem, size_t mem_sz)
Allocates memory for an array,zeroes it out.
void arena_dealloc (size_t n)
Deallocate all objects from a lifetime, when their time is up, but retain the memory for the allocatation of a new set of objects in another lifetime.
void arena_create (size_t n, size_t chunk_sz)
Creates a ready to use arena, and configures the arena to support a chunk_sz.
void arena_destroy (size_t n)
Destroys an arena frees all memory.
Variables
static const ptrdiff_t c128K = 128 * 1024
constant for 128K, which is max malloc can allocate from core.
static uint32_t ARENAS_MAX
static Arena * first
A head pointer to the first arena.
static Arena ** arenas
Backing Array for accessing and using arenas.
static size_t * arena_chunk_sz
Standard chunk size for arena.
static const char * msgBadArena = "Bad arena %lu: max arena: %d see ARENAS_MAX in core_arena.h\n"
error message string for an out of range arena numberer.
const ptrdiff_t ARENA_HEADER_SIZE = sizeof(Arena)
Arena Header Size.
static char * ename []
size_t ARENAS_MAX_ALLOC
int16_t core_arena_log_level
Defines our current log level, if compiled in.
static size_t tot_mem_usage
static size_t * arenas_mem_malloced
>Total usage in bytes.
static size_t * arenas_mem_malloced_count
>Amount of ram allocated per arena.
static size_t * arenas_mem_mmapped
>Number of allocations of ram per arenas.
static size_t * arenas_mem_mmapped_count
>Amount of ram mmapped per arena (>128K).
static size_t * arenas_mem_served
>Number of mmapped ram per arena.
static size_t * arenas_mem_served_count
>Amount of ram served through arena_alloc/calloc
static size_t * arenas_max_chunk_size
>Number of servings of ram per arena.
static size_t * arenas_max_mem_request
‍For logging max chunk size for each arena.
static size_t * arenas_min_mem_request
‍For logging largest memory request for each arena.
static size_t * arenas_avg_mem_request
‍For logging smallest memory request for each arena.
static const char * alloc_emsg = "%s: arena[%u] The chunk_sz requested is to small: %d\n"
static const char * alloc_emsg2
static const char * alloc_emsg3
static bool arenas_initialized =false
Detailed Description
A general purpose arena allocation strategy that is based on malloc.
It is simple, you can't resize previously allocated memory, and it shouldn't break during production, if it breaks, then we exit with an EXIT_FAILURE. So, if you need a hashtable, then you should allocate the resizeable array with calloc, so you can resize that with realloc, and allocate the hashes from the arena. This arena allocation strategy uses malloc intrinisically, if you want other schemes than malloc provides you should look elsewhere.
Definition in file core_arena.c.
Macro Definition Documentation
ERR_BUF_SIZE
#define ERR_BUF_SIZE 500
LOG_BUF_SIZE
#define LOG_BUF_SIZE 200
Function Documentation
ram_avail()
static size_t ram_avail (void) inline static
Returns the physically available ram.
Definition at line 203 of file core_arena.c.
{
    long avail_phys_pages, page_size;
    long long mem_avail;
    if ((avail_phys_pages = sysconf(_SC_AVPHYS_PAGES)) == -1 ){
        _errmsg_write("ram_avail: sysconf(_SC_AVPHYS_PAGES) failed. Aborting.%s","\n");
        exit(EXIT_FAILURE);
    }
    if ((page_size = sysconf(_SC_PAGESIZE)) == -1) {
        _errmsg_write("ram_avail: sysconf(_SC_PAGESIZE) failed. Aborting.%s","\n");
        exit(EXIT_FAILURE);
    }
    if ((size_t)page_size > -1ULL/avail_phys_pages) {
        fprintf(stderr,"ram_avail: needs bigger datatypes to hold available ram!\n");
        exit(EXIT_FAILURE);
    }
    mem_avail = avail_phys_pages * page_size ;
    if ( mem_avail > PTRDIFF_MAX ) {
        fprintf(stderr,"ram_avail: needs bigger datatypes to hold available ram!\n");
        exit(EXIT_FAILURE); // Overflow conditions.
    }
    return (size_t) mem_avail ;
}
References _errmsg_write().
Referenced by arena_init_arenas().
system_page_size()
long system_page_size (void)
Returns the system viritual memory page_size.
Definition at line 190 of file core_arena.c.
{
    long page_size;
    if ((page_size = sysconf(_SC_PAGESIZE)) == -1) {
        _errmsg_write("system_page_size: sysconf(_SC_PAGESIZE) failed. Aborting.%s","\n");
        exit(EXIT_FAILURE);
    }
    return page_size ;
}
References _errmsg_write().
Variable Documentation
ARENAS_MAX_ALLOC
size_t ARENAS_MAX_ALLOC
Definition at line 183 of file core_arena.c.
Referenced by _alloc(), _arena_init(), arena_alloc(), arena_calloc(), and arena_init_arenas().