core_arena: Allocation functions.
Allocation functions.
User functions
Functions that allocates memory from the arena to your program.
Functions
void * arena_alloc (size_t n, size_t mem_sz)
Allocates memory for an object from an arena.
void * arena_calloc (size_t n, size_t nelem, size_t mem_sz)
Allocates memory for an array,zeroes it out.
void arena_dealloc (size_t n)
Deallocate all objects from a lifetime, when their time is up, but retain the memory for the allocatation of a new set of objects in another lifetime.
Detailed Description
Functions that allocates memory from the arena to your program.
Function Documentation
arena_alloc()
void * arena_alloc (size_t n, size_t mem_sz)
Allocates memory for an object from an arena.
Define the number of arenas you need.
Parameters
n The index of the arena to request memory from.
mem_sz The amount of memory we want to allocate.
Just calls _alloc(), if there isn't enough memory to satisfy the request.
Todo:
tests and error messages and EXIT_FAILURE
Definition at line 847 of file core_arena.c.
{
    assert( arenas_initialized == true ) ;
    if ( n >= ARENAS_MAX ) {
        fprintf( stderr, msgBadArena, n, ARENAS_MAX );
        abort(  ); // Overflow conditions.
    }
    static const char *emsg = "arena_alloc: arena[%u]: Couldn't allocate memory for arena with mem_pd: %lu.\n" ;
    static const char *emsg2 = "arena_alloc: arena[%u]: Couldn't allocate memory of size_t %ld.\n"
        "The request is larger than ARENAS_MAX_ALLOC: %lu. ";
    static const char *emsg3 = "arena_alloc: arena[%u]: Couldn't allocate memory of size_t %ld.\n"
        "The request is larger than memory available: %lu. ";
   // First reject anything nonsensical or excessively large .
    if ( mem_sz == 0 || mem_sz > PTRDIFF_MAX ) {
        return NULL; // request impossibly large (out of memory)
    }
    void *p;
    p = arenas[n]->begin; // start of buffer to allocate.
    ptrdiff_t mem_pd = mem_sz;
    ptrdiff_t padding = -mem_pd & ( MAX_ALIGN - 1 );
    mem_pd += padding;
    if ( mem_pd < ( ptrdiff_t ) mem_sz || (  mem_pd   > (PTRDIFF_MAX - ARENA_HEADER_SIZE) ) ) {
        fprintf( stderr, emsg,n, ( size_t ) mem_pd );
        exit(EXIT_FAILURE);
    } else if (mem_pd > (ssize_t)ARENAS_MAX_ALLOC ) {
        fprintf( stderr, emsg2,n, ( size_t ) mem_pd, ARENAS_MAX_ALLOC );
        exit(EXIT_FAILURE);
    } else if (mem_pd > (ssize_t) (ARENAS_MAX_ALLOC - tot_mem_usage) ) {
        fprintf( stderr, emsg3,n, (size_t) mem_pd, (ARENAS_MAX_ALLOC-tot_mem_usage) );
        exit(EXIT_FAILURE);
    }
    ptrdiff_t gauge = (ptrdiff_t)arenas[n]->begin + mem_pd ;
    assert( gauge >= 0) ;
    if ( gauge  > (ptrdiff_t) arenas[n]->end ) {
       // padding is already added to mem_pd here.
        p = _alloc( &arenas[n], mem_pd, n );
    } else { // zero out last byte and padding
        arenas[n]->begin += mem_pd ;
        for ( char *zptr = arenas[n]->begin - ( padding + 1 ); zptr < arenas[n]->begin; zptr++ ) {
             *zptr = '\0';
         }
        if ( gauge < (ptrdiff_t) (arenas[n]->end - MAX_ALIGN) ) {
            arenas[n]->begin += MAX_ALIGN ;
        }
#ifndef CORE_ARENA_NO_LOGGING
    if (core_arena_log_level >= FULL_ARENA_LOGGING )  {
        mem_pd -= padding ;
        arenas_mem_served[n] += mem_pd ;
        arenas_mem_served_count[n] += 1 ;
        if ( mem_pd > (ptrdiff_t) arenas_max_mem_request[n] ) {
            arenas_max_mem_request[n] = mem_pd ;
        }
        if ( (size_t) mem_pd <  arenas_min_mem_request[n] ) {
            arenas_min_mem_request[n] = mem_pd ;
        }
        arenas_avg_mem_request[n] = arenas_mem_served[n] / arenas_mem_served_count[n] ;
    }
#endif
    }
    return p;
}
References _alloc(), ARENA_HEADER_SIZE, arenas, arenas_avg_mem_request, arenas_initialized, ARENAS_MAX, ARENAS_MAX_ALLOC, arenas_max_mem_request, arenas_mem_served, arenas_mem_served_count, arenas_min_mem_request, arena::begin, core_arena_log_level, arena::end, FULL_ARENA_LOGGING, MAX_ALIGN, msgBadArena, and tot_mem_usage.
Referenced by arena_calloc().
arena_calloc()
void * arena_calloc (size_t n, size_t nelem, size_t mem_sz)
Allocates memory for an array,zeroes it out.
Parameters
n The arena that is the "owner" of the allocation.
nelem The number of elements in the array.
mem_sz The size of the individual memoryry..
Great for when you need fully initialized memory.
Todo:
change n from size_t to uint32_t?
Definition at line 928 of file core_arena.c.
{
    assert( arenas_initialized == true ) ;
    if ( n >= ARENAS_MAX ) {
        fprintf( stderr, msgBadArena, n, ARENAS_MAX );
        exit(EXIT_FAILURE);
    }
    static const char *emsg = "arena_calloc: arena[%u]: Couldn't allocate memory for array with mem_ll: %ld.\n"
        "The request is larger than ARENAS_MAX_ALLOC: %lu. ";
    static const char *emsg2 = "arena_calloc: arena[%u]: Couldn't allocate memory for array with %ld nelem of size_t %ld.\n"
        "The request is larger than ARENAS_MAX_ALLOC: %lu. ";
    static const char *emsg3 = "arena_calloc: arena[%u]: Couldn't allocate memory for array with %ld nelem of size_t %ld.\n"
        "The request is larger than memory available: %lu. ";
    assert( mem_sz > 0 ) ;
    long long mem_ll ;
    if (nelem > -1ULL/mem_sz) {
        fprintf( stderr, emsg2, (size_t) nelem, ( size_t ) mem_sz, ARENAS_MAX_ALLOC );
        exit(EXIT_FAILURE);
    } else {
        mem_ll = nelem * mem_sz;
    }
    if ( mem_ll <= 0 ) { // nelem was 0
        return NULL;
    } else if ( mem_ll > PTRDIFF_MAX ) {
        fprintf( stderr, emsg,(int)n, ( size_t ) mem_ll, ARENAS_MAX_ALLOC);
        exit(EXIT_FAILURE);
    } else if (mem_ll > (ssize_t)ARENAS_MAX_ALLOC) {
        fprintf( stderr, emsg,(int)n, ( size_t ) mem_ll, ARENAS_MAX_ALLOC );
        exit(EXIT_FAILURE);
    } else if ((size_t)mem_ll >  ARENAS_MAX_ALLOC - tot_mem_usage ) {
        fprintf( stderr, emsg3,(int)n, (size_t) nelem, ( size_t ) mem_sz, (ARENAS_MAX_ALLOC-tot_mem_usage) );
        exit(EXIT_FAILURE);
    } else {
        void *ptr = arena_alloc( n, (size_t) mem_ll ); // Logging of memory is done in arena_alloc.
        return memset( ptr, 0, (size_t) mem_ll );
    }
}
References arena_alloc(), arenas_initialized, ARENAS_MAX, ARENAS_MAX_ALLOC, msgBadArena, and tot_mem_usage.
arena_dealloc()
void arena_dealloc (size_t n)
Deallocate all objects from a lifetime, when their time is up, but retain the memory for the allocatation of a new set of objects in another lifetime.
Parameters
n The index of the arena to deallocate.
The memory aren't freed from the arena, so it is available for quick reuse.
Definition at line 976 of file core_arena.c.
{
    assert( arenas_initialized == true ) ;
    if ( n >= ARENAS_MAX ) {
        fprintf( stderr, msgBadArena, n, ARENAS_MAX );
        abort(  ); // Overflow conditions.
    }
    arenas[n] = first[n].next;
    if ( arenas[n] ) {
        arenas[n]->begin = ( char * ) arenas[n] + sizeof *arenas[n];
       // Works out beautifully with _alloc(),  which resets.
    } else {
        arenas[n] = &first[n];
    }
}
References arenas, arenas_initialized, ARENAS_MAX, arena::begin, first, msgBadArena, and arena::next.