core_arena: Allocation functions.
Allocation functions.
User functions
Functions
void * arena_alloc (size_t n, size_t mem_sz)
Allocates memory for an object from an arena.
void * arena_calloc (size_t n, size_t nelem, size_t mem_sz)
Allocates memory for an array,zeroes it out.
void arena_deallocate (size_t n)
Deallocate all objects from a lifetime, when their time is up, but retain the memory for the allocatation of a new set of objects in another lifetime.
Detailed Description
Function Documentation
arena_alloc()
void* arena_alloc (size_t n, size_t mem_sz)
Allocates memory for an object from an arena.
Parameters
n The index of the arena to request memory from.
mem_sz The amount of memory we want to allocate.
Just calls _alloc(), if there isn't enough memory to satisfy the request.
Definition at line 385 of file core_arena.c.
 {
     if ( n >= ARENAS_MAX ) {
         fprintf( stderr, msgBadArena, n, ARENAS_MAX );
         abort(  ); // Overflow conditions.
     }
     static const char *emsg = "arena_alloc: Couldn't allocate memory for arena with mem_pd: %lu.\n" "Aborting.";
    // First reject anything nonsensical or excessively large .
     if ( mem_sz == 0 || mem_sz > PTRDIFF_MAX ) {
         return NULL; // request impossibly large (out of memory)
     }
     void *p;
     p = arenas[n]->begin;
     ptrdiff_t mem_pd = mem_sz;
     ptrdiff_t padding = -mem_pd & ( MAX_ALIGN - 1 );
     mem_pd += padding;
     if ( mem_pd < ( ptrdiff_t ) mem_sz || (  mem_pd   > (PTRDIFF_MAX - _AHS) ) ) {
         fprintf( stderr, emsg, ( size_t ) mem_pd );
         abort(  ); // Overflow conditions.
     }
     ptrdiff_t gauge = (ptrdiff_t)arenas[n]->begin + mem_pd ;
     assert( gauge >= 0) ;
     if ( gauge  >= (ptrdiff_t) arenas[n]->end ) {
        // padding is already added to mem_pd here.
         p = _alloc( &arenas[n], mem_sz, n );
     } else { // zero out last byte and padding
         arenas[n]->begin += mem_pd ;
         for ( char *zptr = arenas[n]->begin - ( padding + 1 ); zptr < arenas[n]->begin; zptr++ ) {
             *zptr = '\0';
         }
     }
 #if ARENAS_LOG_LEVEL > 1
     allocated_memory[n] += mem_sz;
     allocation_memory_count[n] += 1;
 #endif
     return p;
 }
References _AHS, _alloc(), arenas, ARENAS_MAX, arena::begin, arena::end, MAX_ALIGN, and msgBadArena.
Referenced by arena_calloc().
arena_calloc()
void* arena_calloc (size_t n, size_t nelem, size_t mem_sz)
Allocates memory for an array,zeroes it out.
Parameters
n The arena that is the "owner" of the allocation.
nelem The number of elements in the array.
mem_sz The size of the individual memoryry..
Great for when you need fully initialized memory.
Definition at line 436 of file core_arena.c.
 {
     if ( n >= ARENAS_MAX ) {
         fprintf( stderr, msgBadArena, n, ARENAS_MAX );
         abort(  ); // Overflow conditions.
     }
     static const char *emsg = "arena_calloc: Couldn't allocate memory for array with mem_ll: %ld.\n"
         "The request is larger than ARENAS_MAX_ALLOC: %lu. ";
     static const char *emsg2 = "arena_calloc: Couldn't allocate memory for array with %ld nelem of size_t %ld.\n"
         "The request is larger than ARENAS_MAX_ALLOC: %lu. ";
     assert( mem_sz > 0 ) ;
     long long mem_ll ;
     if (nelem > -1ULL/mem_sz) {
         fprintf( stderr, emsg2, (size_t) nelem, ( size_t ) mem_ll, ARENAS_MAX_ALLOC );
         abort(  ); // Overflow conditions.
     } else {
         mem_ll = nelem * mem_sz;
     }
     if ( mem_ll <= 0 ) { // nelem was 0
         return NULL;
     } else if ( mem_ll > PTRDIFF_MAX ) {
         fprintf( stderr, emsg, ( size_t ) mem_ll, ARENAS_MAX_ALLOC);
         abort(  ); // Overflow conditions.
     } else if (mem_ll > ARENAS_MAX_ALLOC) {
         fprintf( stderr, emsg, ( size_t ) mem_ll, ARENAS_MAX_ALLOC );
         abort(  ); // Overflow conditions.
     } else {
         size_t mem_req = ( size_t ) mem_ll;
         void *ptr = arena_alloc( n, mem_req ); // Any logging of memory
                                                // allocatations happens here!
         return memset( ptr, 0, mem_req );
     }
 }
References arena_alloc(), ARENAS_MAX, ARENAS_MAX_ALLOC, and msgBadArena.
arena_deallocate()
void arena_deallocate (size_t n)
Deallocate all objects from a lifetime, when their time is up, but retain the memory for the allocatation of a new set of objects in another lifetime.
Parameters
n The index of the arena to deallocate.
The memory aren't freed from the arena, so it is available for quick reuse.
Definition at line 480 of file core_arena.c.
 {
     if ( n >= ARENAS_MAX ) {
         fprintf( stderr, msgBadArena, n, ARENAS_MAX );
         abort(  ); // Overflow conditions.
     }
     arenas[n] = first[n].next;
     if ( arenas[n] ) {
         arenas[n]->begin = ( char * ) arenas[n] + sizeof *arenas[n];
        // Works out beautifully with _alloc().
     } else {
         arenas[n] = &first[n];
     }
 }
References arenas, ARENAS_MAX, arena::begin, first, msgBadArena, and arena::next.