core_arena: Error and Log message functions.
Error and Log message functions.
This module is used for both logging and error messages.
Macros
#define MAX_ENAME 133
Maximum length for an error name.
Functions
static char * _errmsg_format (int err, const char *format, va_list ap)
static void _errmsg_write (const char *format,...)
static char * _logmsg_format (const char *format, va_list ap)
static void _logmsg_write (const char *format,...)
Also used for user errors that doesn't solicit any error number.
Variables
static char * ename []
Detailed Description
This module is used for both logging and error messages.
Macro Definition Documentation
MAX_ENAME
#define MAX_ENAME 133
Maximum length for an error name.
Definition at line 103 of file core_arena.c.
Function Documentation
_errmsg_format()
static char * _errmsg_format (int err, const char * format, va_list ap) inline static
Definition at line 105 of file core_arena.c.
{
#define ERR_BUF_SIZE 500
    static char buf[ERR_BUF_SIZE],
     userMsg[ERR_BUF_SIZE],
     errText[ERR_BUF_SIZE];
    vsnprintf( userMsg, ERR_BUF_SIZE, format, ap );
    snprintf( errText, ERR_BUF_SIZE, " [%s %s]", ( err > -1 && err <= MAX_ENAME ) ? ename[err] : "?UNKNOWN?", strerror( err ) );
#if __GNUC__ >= 7
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wformat-truncation"
#endif
    snprintf( buf, ERR_BUF_SIZE, "ERROR%s %s\n", errText, userMsg );
#if __GNUC__ >= 7
#pragma GCC diagnostic pop
#endif
    return buf;
}
References ename, ERR_BUF_SIZE, and MAX_ENAME.
Referenced by _errmsg_write().
_errmsg_write()
static void _errmsg_write (const char * format, ...) inline static
Definition at line 127 of file core_arena.c.
{
    char *formatted_emsg=NULL;
    va_list argList;
    int savedErrno;
    savedErrno = errno;         /* In case we change it here */
    va_start( argList, format );
    formatted_emsg = _errmsg_format(errno,format,argList );
    va_end( argList );
    fflush( stdout );       /* Flush any pending stdout */
    fputs( formatted_emsg, stderr );
    fflush( stderr );           /* In case stderr is not line-buffered */
    errno = savedErrno;
}
References _errmsg_format().
Referenced by arena_create(), arena_init_arenas(), get_log_level(), ram_avail(), and system_page_size().
_logmsg_format()
static char * _logmsg_format (const char * format, va_list ap) inline static
Definition at line 147 of file core_arena.c.
{
#define LOG_BUF_SIZE 200
    static char buf[LOG_BUF_SIZE];
    vsnprintf( buf, LOG_BUF_SIZE, format, ap );
    return buf;
}
References LOG_BUF_SIZE.
Referenced by _logmsg_write().
_logmsg_write()
static void _logmsg_write (const char * format, ...) inline static
Also used for user errors that doesn't solicit any error number.
Definition at line 158 of file core_arena.c.
{
    char *formatted_emsg=NULL;
    va_list argList;
    int savedErrno;
    savedErrno = errno;         /* In case we change it here */
    va_start( argList, format );
    formatted_emsg = _logmsg_format(format,argList );
    va_end( argList );
    fflush( stdout );       /* Flush any pending stdout */
    fputs( formatted_emsg, stderr );
    fflush( stderr );           /* In case stderr is not line-buffered */
    errno = savedErrno;
}
References _logmsg_format().
Referenced by get_log_level().
Variable Documentation
ename
char* ename[] static
Definition at line 68 of file core_arena.c.
Referenced by _errmsg_format().