core_arena: Indiviual Arena initialization and destruction functions.
Indiviual Arena initialization and destruction functions.
User functions
Functions that configures an individual arena, and frees memory back when done.
Functions
void arena_create (size_t n, size_t chunk_sz)
Creates a ready to use arena, and configures the arena to support a chunk_sz.
void arena_destroy (size_t n)
Destroys an arena frees all memory.
Detailed Description
Functions that configures an individual arena, and frees memory back when done.
Function Documentation
arena_create()
void arena_create (size_t n, size_t chunk_sz)
Creates a ready to use arena, and configures the arena to support a chunk_sz.
Parameters
n The index of the arena to destroy.
chunk_sz The nominal size of the arena to allocate memory from.
Aborts if something is wrong.
Todo:
reuse error message as well.
Todo:
: first step, next is to subtract AHS. (ideal sizes pagesize wise).
Definition at line 1007 of file core_arena.c.
{
    assert( arenas_initialized == true ) ;
#ifndef CORE_ARENA_NO_LOGGING
    if (core_arena_log_level > NO_ARENA_LOGGING ) {
        arenas_min_mem_request[n] = SIZE_MAX ;
        static bool log_inited;
        if ( !log_inited ) {
            if(atexit( report_memory_usage )<0) {
                _errmsg_write("arena_create: failed installing atexit handler.%s","\n");
                exit(EXIT_FAILURE);
            }
            log_inited = true;
        }
    }
#endif
    if ( n >= ARENAS_MAX ) {
        fprintf( stderr, msgBadArena, n, ARENAS_MAX );
        abort(  ); // Overflow conditions.
    }
    static const char *emsg = "arena_create: Couldn't allocate memory for arena with chunk_sz: %lu.";
   // First reject anything nonsensical or excessively large .
    if ( chunk_sz == 0 || chunk_sz > PTRDIFF_MAX ) {
        fprintf( stderr, emsg, chunk_sz );
        abort(  );
    }
    first[n].next = _arena_init( n, chunk_sz );
    first[n].chunk_sz = first[n].next->chunk_sz ;
    // default chunk_sz for each block for arena[n] adjusted for padding ;
    if ( first[n].next == NULL ) {
        fprintf( stderr, emsg, chunk_sz );
        abort(  );
    }
    arenas[n] = first[n].next;
}
References _arena_init(), _errmsg_write(), arenas, arenas_initialized, ARENAS_MAX, arenas_min_mem_request, arena::chunk_sz, core_arena_log_level, first, msgBadArena, arena::next, NO_ARENA_LOGGING, and report_memory_usage().
arena_destroy()
void arena_destroy (size_t n)
Destroys an arena frees all memory.
Parameters
n The index of the arena to destroy.
All memory is released into the common pool of free memory.
Todo:
log freeing during destroy with block count;
Definition at line 1056 of file core_arena.c.
{
    assert( arenas_initialized == true ) ;
    if ( n >= ARENAS_MAX ) {
        fprintf( stderr, msgBadArena, n, ARENAS_MAX );
        abort(  ); // Overflow conditions.
    }
    Arena *p,
    *q;
    for ( p = ( Arena * ) ( first[n].next ); p; ) {
        q = p->next;
        free( p );
        p = q;
    }
#ifndef CORE_ARENA_NO_LOGGING
    if (core_arena_log_level >= LOG_CHUNK_MALLOCS  ) {
        tot_mem_usage -= arenas_mem_malloced[n] ;
        tot_mem_usage -= arenas_mem_mmapped[n] ;
    }
#endif
    first[n].next = NULL;
    arenas[n] = NULL;
}
References arenas, arenas_initialized, ARENAS_MAX, arenas_mem_malloced, arenas_mem_mmapped, core_arena_log_level, first, LOG_CHUNK_MALLOCS, msgBadArena, arena::next, and tot_mem_usage.